site_name: LinguSID Documentation
site_url: https://your-github-username.github.io/LinguSID/
repo_url: https://github.com/wahyulingu/LinguSID
repo_name: wahyulingu/LinguSID
edit_uri: edit/develop/docs/

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

nav:
  - Home: index.md
  - Installation: installation.md
  - Contribution: contribution.md
  - Architecture: architecture.md
  - API Documentation: api.md
  - Troubleshooting: troubleshooting.md
  - License: license.md

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - toc:
      permalink: true